---

- hosts: dcnm_controllers
  gather_facts: false

  vars:
    fabric: DevNet_Fabric

  tasks:
    - name: Create overlay network
      cisco.dcnm.dcnm_network:
        fabric: "{{ fabric }}"
        state: merged
        config:
        - net_name: Ansible_Network
          vrf_name: Ansible_VRF
          net_template: Default_Network_Universal
          net_extension_template: Default_Network_Extension_Universal
          gw_ip_subnet: '172.30.100.1/24'
          attach:
          - ip_address: 10.10.20.173
            ports: [Ethernet1/11]
            int_desc: "Ansible attached interface"
            deploy: true
          - ip_address: 10.10.20.174
            ports: [Ethernet1/11]
            int_desc: "Ansible attached interface"
            deploy: true